FROM trophime/magnettools:1.1.0-bookworm-poetry-1.8.4

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 DEBIAN_FRONTEND=noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections

USER root
RUN apt-get update \
    && apt-get install -y iputils-ping vim-nox emacs-nox \
    && apt-get install -y wait-for-it \
    && apt-get install -y debconf-utils \
    && apt-get install -y libpq-dev

USER feelpp

