FROM trophime/magnettools:1.1.0-bookworm-poetry-1.8.4
#FROM trophime/magnettools:bullseye-poetry

ARG USERNAME=feelpp
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 DEBIAN_FRONTEND=noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections

USER root
RUN apt-get update \
    && apt-get install -y iputils-ping vim-nox emacs-nox \
    && apt-get install -y wait-for-it \
    && apt-get install -y debconf-utils \
    && apt-get install -y libpq-dev

RUN echo "create local user $USERNAME (uid=${USER_UID}, gid=${USER_GID})" \
    && echo "group: $(getent group $USER_GID)" \
    && echo "user: $(getent passwd $USER_UID)" \
    # Create a non-root user to use if preferred - see https://aka.ms/vscode-remote/containers/non-root-user.\
    && if [ ! $(getent group $USER_GID) ]; then groupadd --gid $USER_GID $USERNAME; fi \
    && if [ ! $(getent passwd $USER_UID) ]; then useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME; fi \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && echo "local user $(getent group $USER_GID)" \
    && echo "local user $(getent passwd $USER_UID)" \
    && mkdir -p ~${USERNAME}/.ssh/ \
    # add github ssh key\
    && ssh-keyscan github.com >> ~${USERNAME}/.ssh/known_hosts \
    && chown -R $USER_GID:$USER_UID ~${USERNAME}/.ssh

USER $USERNAME

