version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: magnetdb-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./network_internal.conf:/etc/nginx/network_internal.conf
    environment:
    - NETWORK_ACCESS=internal
    # networks:
    #   - proxy-tier

  lemonldap-app:
    # image: tiredofit/lemonldap:latest
    image: tiredofit/lemonldap:2.0.24
    container_name: lemonldap-app
    volumes:
    #- ../magnetdb-data/lemonldap-ng-data/etc/lemonldap-ng:/etc/lemonldap-ng
    - ../magnetdb-data/lemonldap-ng-data/conf:/var/lib/lemonldap-ng/conf
    #- ../magnetdb-data/lemonldap-ng-data/sessions:/var/lib/lemonldap-ng/sessions
    #- ../magnetdb-data/lemonldap-ng-data/psessions:/var/lib/lemonldap-ng/psessions
    - ../magnetdb-data/logs:/www/logs
    #- ./assets/custom:/assets/custom
    environment:
    - VIRTUAL_HOST=sso.grenoble.lncmi.local,manager.sso.grenoble.lncmi.local,handler.sso.grenoble.lncmi.local
    # - VIRTUAL_NETWORK=nginx-proxy
    # - VIRTUAL_PROTO=https
    # - VIRTUAL_PORT=443
    - NETWORK_ACCESS=internal
    # - LETSENCRYPT_HOST=sso.grenoble.lncmi.local,manager.sso.grenoble.lncmi.local,handler.sso.grenoble.lncmi.local
    # - LETSENCRYPT_EMAIL=christophe.trophime@lncmi.cnrs.fr

    - CONTAINER_NAME=lemonldap-app

    - DOMAIN_NAME=sso.grenoble.lncmi.local
    - API_HOSTNAME=api.manager.sso.grenoble.lncmi.local
    - MANAGER_HOSTNAME=manager.sso.grenoble.lncmi.local
    - PORTAL_HOSTNAME=sso.grenoble.lncmi.local
    - HANDLER_HOSTNAME=handler.sso.grenoble.lncmi.local
    - LOG_LEVEL=debug
    links:
      - nginx-proxy
    # networks:
    #   - proxy-tier
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always
      

  redis:
    image: redis
    container_name: redis-app
    ports:
      - 6379:6379

  postgres:
    image: postgres:13
    container_name: postgres-app
    ports:
      - 5432:5432
    environment:
      VIRTUAL_HOST: postgres.grenoble.lncmi.local
      POSTGRES_USER: magnetdb
      POSTGRES_PASSWORD: magnetdb
    volumes:
      - ../magnetdb-data/postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-app
    environment:
      VIRTUAL_HOST: pgadmin.grenoble.lncmi.local
      PGADMIN_DEFAULT_EMAIL: christophe.trophime@lncmi.cnrs.fr
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ../magnetdb-data/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:80
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: magnetdb-minio
    entrypoint: sh
    command: 
      -c 'mkdir -p /data/magnetdb && minio server /data --console-address ":9080"'
    environment:
      VIRTUAL_HOST: minio.grenoble.lncmi.local
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9000:9000
      - 9080:9080
    volumes:
      - ../magnetdb-data/minio-data:/data

  web-app:
    image: node:16
    container_name: magnetdb-webapp
    command:
      - /bin/bash
      - -c
      - |
        yarn add caniuse-lite
        yarn remove caniuse-lite
        yarn install
        yarn serve
    working_dir: /app
    volumes:
      - ./web:/app
    environment:
      VIRTUAL_HOST: magnetdb.grenoble.lncmi.local
    ports:
      - 8080:8080

  web-api:
    build: .
    privileged: true
    container_name: magnetdb-api
    command: 
      - /bin/bash
      - -c
      - |
        cd python_magnetsetup
        poetry update
        cd ..
        poetry install
        poetry run uvicorn python_magnetdb.web:app --reload --host 0.0.0.0
    # links:
    #   - web-app
    working_dir: /home/feelpp/test
    network_mode: host
    volumes:
      - .:/home/feelpp/test
      - ../magnetdb-data/poetry-cache:/home/feelpp/.cache/pypoetry
      - ./data/:/data
      - ./images:/images
    # extra_hosts:
    #   - sso.grenoble.lncmi.local:127.0.0.1
    depends_on:
      - lemonldap-app
      - redis
      - postgres
      - minio
    environment:
      S3_ENDPOINT: minio.grenoble.lncmi.local:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: magnetdb
      REDIS_ADDR: redis://redis.grenoble.lncmi.local:6379/0
      DATABASE_HOST: postgres.grenoble.lncmi.local
      IMAGES_DIR: /images

  web-worker:
    build: .
    privileged: true
    container_name: magnetdb-worker
    command:
      - /bin/bash
      - -c
      - |
        cd python_magnetsetup
        poetry update
        cd ..
        poetry install
        watchmedo auto-restart -d ./python_magnetdb/ -p '**/*.py' -- poetry run celery -A python_magnetdb.worker worker --loglevel=info
    working_dir: /home/feelpp/test
    volumes:
      - .:/home/feelpp/test
      - ../magnetdb-data/poetry-cache-worker:/home/feelpp/.cache/pypoetry
      - ./data/:/data
      - ./images:/images
    depends_on:
      - redis
      - postgres
      - minio
    environment:
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: magnetdb
      REDIS_ADDR: redis://redis:6379/0
      DATABASE_HOST: postgres
      IMAGES_DIR: /images

volumes:
  minio-data: {}
  postgres-data: {}
  pgadmin-data: {}
  lemonldap-ng-data: {}

# networks:
#   proxy-tier:
#     external:
#       name: nginx-proxy
