version: '3'
  web-api:
    image: trophime/magnettools:1.0.6-poetry
    container_name: web-api
    command: poetry run uvicorn python_magnetdb.web:app --reload --host 0.0.0.0
    working_dir: /home/feelpp/test
    network_mode: host
    volumes:
      - .:/home/feelpp/test
      - ./poetry-cache:/home/feelpp/.cache/pypoetry
      - ./data/:/data
    links:
      - redis
      - postgres
      - minio
    extra_hosts:
      - handler.sso.grenoble.lncmi.local:127.0.0.1
      - api.manager.sso.grenoble.lncmi.local:127.0.0.1 
      - manager.sso.grenoble.lncmi.local:127.0.0.1
      - sso.grenoble.lncmi.local:127.0.0.1
      - test.sso.grenoble.lncmi:127.0.0.1

    environment:
      S3_ENDPOINT: localhost:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: magnetdb
      REDIS_ADDR: redis://localhost:6379/0
      DATABASE_HOST: localhost
  web-worker:
    image: trophime/magnettools:1.0.6-poetry
    container_name: web-worker
    command: watchmedo auto-restart -d ./python_magnetdb/ -p '**/*.py' -- poetry run celery -A python_magnetdb.worker worker --loglevel=info
    working_dir: /home/feelpp/test
    volumes:
      - .:/home/feelpp/test
      - ./poetry-cache:/home/feelpp/.cache/pypoetry
      - ./data/:/data
    links:
      - redis
      - postgres
      - minio
    environment:
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: magnetdb
      REDIS_ADDR: redis://redis:6379/0
      DATABASE_HOST: postgres
  web-app:
    image: node:16
    command: yarn serve
    container_name: web-app
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - 8080:8080

  redis:
    image: redis
    container_name: redis-app
    ports:
      - 6379:6379

  postgres:
    image: postgres:12
    container_name: postgres-app
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: magnetdb
      POSTGRES_PASSWORD: magnetdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-app
    environment:
      PGADMIN_DEFAULT_EMAIL: christophe.trophime@lncmi.cnrs.fr
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:80
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio-app
    command: server /data --console-address ":9080"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9000:9000
      - 9080:9080
    volumes:
      - ./minio-data:/data

  lemonldap-app:
    # image: tiredofit/lemonldap:2.0-alpine-latest
    image: tiredofit/lemonldap:2.0.24
    container_name: lemonldap-app
    volumes:
    #- ./lemonldap-ng-data/etc/lemonldap-ng:/etc/lemonldap-ng
    - ./lemonldap-ng-data/conf:/var/lib/lemonldap-ng/conf
    #- ./lemonldap-ng-data/sessions:/var/lib/lemonldap-ng/sessions
    #- ./lemonldap-ng-data/psessions:/var/lib/lemonldap-ng/psessions
    - ./logs:/www/logs
    #- ./assets/custom:/assets/custom
    environment:
    - VIRTUAL_HOST=sso.grenoble.lncmi.local,manager.sso.grenoble.lncmi.local,handler.sso.grenoble.lncmi.local
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=sso.grenoble.lncmi.local,manager.sso.grenoble.lncmi.local,handler.sso.grenoble.lncmi.local
    - LETSENCRYPT_EMAIL=christophe.trophime@lncmi.cnrs.fr

    - CONTAINER_NAME=lemonldap-app

    - DOMAIN_NAME=sso.grenoble.lncmi.local
    - API_HOSTNAME=api.manager.sso.grenoble.lncmi.local
    - MANAGER_HOSTNAME=manager.sso.grenoble.lncmi.local
    - PORTAL_HOSTNAME=sso.grenoble.lncmi.local
    - HANDLER_HOSTNAME=handler.sso.grenoble.lncmi.local
    - LOG_LEVEL=debug
    networks:
      - proxy-tier
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always
      
volumes:
  minio-data: {}
  postgres-data: {}
  pgadmin-data: {}
  lemonldap-ng-data: {}

networks:
  proxy-tier:
    external:
      name: nginx-proxy
