version: '3'
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: magnetdb
      POSTGRES_PASSWORD: magnetdb
    volumes:
      - postgres:/var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data --console-address ":9080"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9000:9000
      - 9080:9080
    volumes:
      - minio:/data
  ldap:
    image: osixia/openldap
    ports:
      - 389:389
      - 636:636
  lemonldap:
    image: coudot/lemonldap-ng
    ports:
      - 80:80
    environment:
      LOGLEVEL: debug
volumes:
  minio: {}
  postgres: {}
