version: '3'
services:
  redis:
    image: redis
    container_name: redis-app
    ports:
      - 6379:6379

  postgres:
    image: postgres:12
    container_name: postgres-app
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: magnetdb
      POSTGRES_PASSWORD: magnetdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-app
    environment:
      PGADMIN_DEFAULT_EMAIL: christophe.trophime@lncmi.cnrs.fr
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:80
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio-app
    command: server /data --console-address ":9080"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9000:9000
      - 9080:9080
    volumes:
      - ./minio-data:/data

  lemonldap-app:
    # image: tiredofit/lemonldap:2.0-alpine-latest
    image: tiredofit/lemonldap:latest
    container_name: lemonldap-app
    volumes:
    - ./lemonldap-ng-data/etc/lemonldap-ng:/etc/lemonldap-ng
    - ./lemonldap-ng-data/conf:/var/lib/lemonldap-ng/conf
    - ./lemonldap-ng-data/sessions:/var/lib/lemonldap-ng/sessions
    - ./lemonldap-ng-data/psessions:/var/lib/lemonldap-ng/psessions
    - ./logs:/www/logs
    #- ./assets/custom:/assets/custom
    environment:
    - VIRTUAL_HOST=sso.grenoble.lncmi.local,manager.sso.grenoble.lncmi.local,handler.sso.grenoble.lncmi.local
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=sso.grenoble.lncmi.local,manager.sso.grenoble.lncmi.local,handler.sso.grenoble.lncmi.local
    - LETSENCRYPT_EMAIL=christophe.trophime@lncmi.cnrs.fr

    - CONTAINER_NAME=lemonldap-app

    - DOMAIN_NAME=sso.grenoble.lncmi.local
    - API_HOSTNAME=api.manager.sso.grenoble.lncmi.local
    - MANAGER_HOSTNAME=manager.sso.grenoble.lncmi.local
    - PORTAL_HOSTNAME=sso.grenoble.lncmi.local
    - HANDLER_HOSTNAME=handler.sso.grenoble.lncmi.local
    - LOG_LEVEL=debug
    networks:
      - proxy-tier
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always
    ports:
      - 80:80
      - 443:443
      
volumes:
  minio-data: {}
  postgres-data: {}
  pgadmin-data: {}
  lemonldap-ng-data: {}

networks:
  proxy-tier:
    external:
      name: nginx-proxy
