version: '3'
services:
  web-api:
    image: trophime/magnettools:poetry
    command: poetry run uvicorn python_magnetdb.web:app --reload --host 0.0.0.0
    working_dir: /home/feelpp/test
    volumes:
      - .:/home/feelpp/test
      - ./poetry-cache:/home/feelpp/.cache/pypoetry
    ports:
      - 8000:8000
    links:
      - redis
      - postgres
      - minio
    environment:
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: magnetdb
      REDIS_ADDR: redis://redis:6379/0
      DATABASE_HOST: postgres
  web-worker:
    image: trophime/magnettools:poetry
    command: poetry run celery -A python_magnetdb.worker worker --loglevel=info
    working_dir: /home/feelpp/test
    volumes:
      - .:/home/feelpp/test
      - ./poetry-cache:/home/feelpp/.cache/pypoetry
    links:
      - redis
      - postgres
      - minio
    environment:
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: magnetdb
      REDIS_ADDR: redis://redis:6379/0
      DATABASE_HOST: postgres
  redis:
    image: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: magnetdb
      POSTGRES_PASSWORD: magnetdb
    volumes:
      - postgres:/var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data --console-address ":9080"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9000:9000
      - 9080:9080
    volumes:
      - minio:/data
  lemonldap:
    image: coudot/lemonldap-ng
    ports:
      - 80:80
    environment:
      LOGLEVEL: debug
    volumes:
      - lemonldap-etc:/etc/lemonldap-ng
      - lemonldap-var:/var/lib/lemonldap-ng
volumes:
  minio: {}
  postgres: {}
  lemonldap-etc: {}
  lemonldap-var: {}
