version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    container_name: magnetdb-reverse-proxy
    # Enables the web UI and tells Traefik to listen to docker
    command:
      --api.insecure=true
      --log.level="DEBUG"
      --providers.docker
      --providers.docker.exposedbydefault=false
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8088:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  lemonldapapp:
    image: tiredofit/lemonldap:2.0.24
    container_name: lemonldap-app
    volumes:
    - ../magnetdb-data/lemonldap-ng-data/conf:/var/lib/lemonldap-ng/conf
    - ../magnetdb-data/logs:/www/logs
    #- ./assets/custom:/assets/custom
    environment:
    - VIRTUAL_HOST=sso.grenoble.lncmi.local,manager.sso.grenoble.lncmi.local,handler.sso.grenoble.lncmi.local
    - CONTAINER_NAME=lemonldap-app

    - DOMAIN_NAME=sso.grenoble.lncmi.local
    - API_HOSTNAME=api.manager.sso.grenoble.lncmi.local
    - MANAGER_HOSTNAME=manager.sso.grenoble.lncmi.local
    - PORTAL_HOSTNAME=sso.grenoble.lncmi.local
    - HANDLER_HOSTNAME=handler.sso.grenoble.lncmi.local
    - LOG_LEVEL=debug
    links:
      - reverse-proxy
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lemonldapapp.rule=Host(`sso.grenoble.lncmi.local`,`api.grenoble.lncmi.local`,`manager.sso.grenoble.lncmi.local`,`handler.sso.grenoble.lncmi.local`)"
      

  redis:
    image: redis
    container_name: redis-app
    ports:
      - 6379:6379
    labels:
      - "traefik.enable=true"
    #  - "traefik.http.routers.redis.rule=Host(`redis.grenoble.lncmi.local`)"

  postgres:
    image: postgres:13
    container_name: postgres-app
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: magnetdb
      POSTGRES_PASSWORD: magnetdb
    volumes:
      - ../magnetdb-data/postgres-data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postgres.rule=Host(`postgres.grenoble.lncmi.local`)"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-app
    environment:
      PGADMIN_DEFAULT_EMAIL: christophe.trophime@lncmi.cnrs.fr
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ../magnetdb-data/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.grenoble.lncmi.local`)"

  minio:
    image: minio/minio
    container_name: minio-app
    entrypoint: sh
    command: 
      -c 'mkdir -p /data/magnetdb && minio server /data --console-address ":9080"'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_BROWSER_REDIRECT_URL: http://minio.grenoble.lncmi.local
    ports:
      - 9000:9000
      - 9080:9080
    volumes:
      - ../magnetdb-data/minio-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-http.entrypoints=web"
      - "traefik.http.routers.minio.rule=Host(`minio-storage.grenoble.lncmi.local`)"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.routers.minio-console.rule=Host(`minio.grenoble.lncmi.local`)"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9080"

  webapp:
    image: node:16
    container_name: magnetdb-webapp
    command:
      - /bin/bash
      - -c
      - |
        whoami
        yarn add caniuse-lite
        yarn remove caniuse-lite
        yarn install
        yarn serve
    working_dir: /app
    volumes:
      - ./web:/app
    links:
      - postgres
      - minio
      - lemonldapapp
    # extra_hosts:
    #   - sso.grenoble.lncmi.local:127.0.0.1
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`magnetdb.grenoble.lncmi.local`)"

  webapi:
    build: .
    privileged: true
    container_name: magnetdb-api
    command: 
      - /bin/bash
      - -c
      - |
        cd python_magnetsetup
        poetry update
        cd ..
        poetry install
        poetry run uvicorn python_magnetdb.web:app --reload --host 0.0.0.0
    working_dir: /home/feelpp/test
    # network_mode: host
    ports:
      - 8000:8000
    volumes:
      - .:/home/feelpp/test
      - ../magnetdb-data/poetry-cache:/home/feelpp/.cache/pypoetry
      - ./data/:/data
      - ./images:/images
    depends_on:
      - lemonldapapp
      - webapp
      - postgres
      - minio
    environment:
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: magnetdb
      REDIS_ADDR: redis://redis.grenoble.lncmi.local:6379/0
      DATABASE_HOST: postgres
      IMAGES_DIR: /images
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapi.rule=Host(`magnetdb-api.grenoble.lncmi.local`)"
    #  - "traefik.http.services.webapi.loadbalancer.server.port=8000"

  webworker:
    build: .
    privileged: true
    container_name: magnetdb-worker
    command:
      - /bin/bash
      - -c
      - |
        cd python_magnetsetup
        poetry update
        cd ..
        poetry install
        watchmedo auto-restart -d ./python_magnetdb/ -p '**/*.py' -- poetry run celery -A python_magnetdb.worker worker --loglevel=info
    working_dir: /home/feelpp/test
    volumes:
      - .:/home/feelpp/test
      - ../magnetdb-data/poetry-cache-worker:/home/feelpp/.cache/pypoetry
      - ./data/:/data
      - ./images:/images
    links:
      - redis
      - postgres
      - minio
    environment:
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: magnetdb
      REDIS_ADDR: redis://redis:6379/0
      DATABASE_HOST: postgres
      IMAGES_DIR: /images
    labels:
      - "traefik.enable=false"
      - "traefik.http.services.webworker.loadbalancer.server.port=80"
     # - "traefik.http.routers.webworker.rule=Host(`magnetdb-worker.grenoble.lncmi.local`)"

volumes:
  minio-data: {}
  postgres-data: {}
  pgadmin-data: {}
  lemonldap-ng-data: {}

