# Generated by Django 5.1.4 on 2024-12-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0006_remove_magnet_cad_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='geometry_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='part',
            name='hts_attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_hts_set', to='python_magnetdb.storageattachment'),
        ),
        migrations.AddField(
            model_name='part',
            name='shape_attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_shape_set', to='python_magnetdb.storageattachment'),
        ),
    ]
