# Generated by Django 5.1.4 on 2024-12-19 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0007_part_geometry_config_part_hts_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='hts_attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_hts', to='python_magnetdb.storageattachment'),
        ),
        migrations.AlterField(
            model_name='part',
            name='shape_attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_shape', to='python_magnetdb.storageattachment'),
        ),
    ]
