# Generated by Django 5.1.4 on 2024-12-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0009_magnetpart_angle_magnetpart_inner_bore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemagnet',
            name='parallax',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sitemagnet',
            name='r_offset',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sitemagnet',
            name='z_offset',
            field=models.FloatField(null=True),
        ),
    ]
