# Generated by Django 5.1.4 on 2025-01-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0010_sitemagnet_parallax_sitemagnet_r_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnet',
            name='type',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
