# Generated by Django 5.1.4 on 2025-01-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0011_magnet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magnetpart',
            name='inner_bore',
        ),
        migrations.RemoveField(
            model_name='magnetpart',
            name='outer_bore',
        ),
        migrations.AddField(
            model_name='magnet',
            name='inner_bore',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='magnet',
            name='outer_bore',
            field=models.FloatField(null=True),
        ),
    ]
