# Generated by Django 5.1.4 on 2025-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0012_remove_magnetpart_inner_bore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magnet',
            name='type',
            field=models.CharField(choices=[('insert', 'INSERT'), ('bitters', 'BITTERS'), ('supras', 'SUPRAS')], max_length=255),
        ),
        migrations.AlterField(
            model_name='part',
            name='type',
            field=models.CharField(choices=[('supra', 'SUPRA'), ('helix', 'HELIX'), ('ring', 'RING'), ('screen', 'SCREEN'), ('lead', 'LEAD'), ('bitter', 'BITTER')], max_length=255),
        ),
    ]
