# Generated by Django 5.1.5 on 2025-01-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0014_magnet_metadata_magnetpart_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnet',
            name='flow_params',
            field=models.JSONField(null=True),
        ),
    ]
