# Generated by Django 5.1.7 on 2025-03-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0015_magnet_flow_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magnet',
            name='geometry_attachment',
        ),
        migrations.AlterField(
            model_name='simulation',
            name='setup_state',
            field=models.JSONField(default=dict),
        ),
    ]
