# Generated by Django 5.2 on 2025-04-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0016_remove_magnet_geometry_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeshAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('axi', 'AXI'), ('3d', 'THREE_DIMENSIONS')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_magnetdb.storageattachment')),
                ('magnet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='python_magnetdb.magnet')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='python_magnetdb.site')),
            ],
            options={
                'db_table': 'mesh_attachments',
            },
        ),
    ]
