# Generated by Django 5.2 on 2025-04-03 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0017_meshattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='mesh_attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_mesh_attachment', to='python_magnetdb.meshattachment'),
        ),
    ]
