# Generated by Django 5.2.5 on 2025-08-18 06:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0018_simulation_mesh_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('index', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of probes string ids', size=None)),
                ('locations', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=3), blank=True, default=list, help_text='List of 3D coordinates as [x, y, z]', size=None)),
                ('metadata', models.JSONField(default=dict)),
                ('magnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_magnetdb.magnet')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='python_magnetdb.part')),
            ],
            options={
                'db_table': 'probes',
            },
        ),
    ]
