# Generated by Django 5.2.5 on 2025-08-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0019_probe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probe',
            name='type',
            field=models.CharField(choices=[('voltage_taps', 'VOLTAGE'), ('temperature', 'TEMPERATURE'), ('magnetic_field', 'BFIELD')], max_length=255),
        ),
    ]
