# Generated by Django 5.2.5 on 2025-08-18 12:20

import python_magnetdb.models.cad_attachment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0020_alter_probe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadattachment',
            name='type',
            field=models.CharField(choices=[('axi', 'AXI'), ('3d', 'THREE_DIMENSIONS')], default=python_magnetdb.models.cad_attachment.CadAttachmentType['THREE_DIMENSIONS'], max_length=255),
        ),
    ]
