# Generated by Django 5.2.5 on 2025-11-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_magnetdb', '0021_cadattachment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='probe',
            old_name='index',
            new_name='labels',
        ),
        migrations.RenameField(
            model_name='probe',
            old_name='locations',
            new_name='points',
        ),
    ]
