# Generated by Django 5.2.9 on 2026-01-27 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("python_magnetdb", "0022_rename_index_probe_labels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="modelaxi_attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="part_modelaxi",
                to="python_magnetdb.storageattachment",
            ),
        ),
    ]
