logLevel: DEBUG
api:
  insecure: true
  dashboard: true
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    http:
      tls:
        certResolver: default
providers:
  file:
    filename: /etc/traefik/tls.yml
